"""Shared fixtures for the tuipet test suite.

The single most important thing this file does is **isolate persistence** so a
test can never touch Joel's real save/settings at ~/.local/share/tuipet/ (a
leaked test save has corrupted the live game before). The `isolate_save`
fixture is autouse, so every test in the suite gets a throwaway save dir.
"""
import pytest
from tuipet.i18n.translator import set_language
set_language("pt")

from tuipet.utils import persistence, persistio


@pytest.fixture(autouse=True)
def isolate_save(tmp_path, monkeypatch):
    """Redirect all persistence I/O into a per-test tmp dir.

    persistence resolves SAVE_PATH/SETTINGS_PATH at call time (`path or <GLOBAL>`),
    so monkeypatching the module globals is enough to fully sandbox it.
    """
    monkeypatch.setattr(persistio, "SAVE_DIR", str(tmp_path))
    monkeypatch.setattr(persistio, "SAVE_PATH", str(tmp_path / "save.json"))
    monkeypatch.setattr(persistio, "SETTINGS_PATH", str(tmp_path / "settings.json"))
    from tuipet.utils.persistence import settings_io, save_io
    monkeypatch.setattr(settings_io, "SETTINGS_PATH", str(tmp_path / "settings.json"))
    monkeypatch.setattr(save_io, "SAVE_PATH", str(tmp_path / "save.json"))
    monkeypatch.setattr(persistence, "SAVE_DIR", str(tmp_path))
    monkeypatch.setattr(persistence, "SAVE_PATH", str(tmp_path / "save.json"))
    monkeypatch.setattr(persistence, "SETTINGS_PATH", str(tmp_path / "settings.json"))
    monkeypatch.setattr(settings_io, "SAVE_DIR", str(tmp_path))
    monkeypatch.setattr(save_io, "SAVE_DIR", str(tmp_path))
    from tuipet.utils.persistence import progress_io
    monkeypatch.setattr(progress_io, "SAVE_DIR", str(tmp_path))
    monkeypatch.setattr(progress_io, "SAVE_PATH", str(tmp_path / "save.json"))
    # module-level write-dedupe caches must not leak between sandboxes: a
    # num already in _ALBUM_SEEN makes album_add() a no-op on the FRESH save
    # (test_egg_guide caught it shadowing test_egg_economy, 2026-07-12)
    from tuipet.utils.persistence import progress_io
    monkeypatch.setattr(progress_io, "_ALBUM_SEEN", set())
    monkeypatch.setattr(persistence, "_ALBUM_SEEN", progress_io._ALBUM_SEEN)
    # sound's volume + wav-cache paths ride persistence.SAVE_DIR at call
    # time since the 2026-07-19 shape sweep -- the SAVE_DIR patch above
    # sandboxes them; only the in-memory volume needs resetting
    from tuipet.utils import sound
    monkeypatch.setattr(sound, "_volume", sound.DEFAULT_VOLUME)
    yield


@pytest.fixture(autouse=True)
def weekday_bits(monkeypatch):
    """Pin weekend_bonus to a weekday (x1.0) so every bit-amount pin in the
    suite is deterministic no matter which real day it runs on. The weekend
    tests exercise _weekend_mult directly / re-patch weekend_bonus to 1.5."""
    from tuipet.core import pet as pet_mod
    monkeypatch.setattr(pet_mod, "weekend_bonus", lambda now=None: 1.0)
    yield


def _by_num():
    import tuipet.data.loaders.data as data
    _, by_num = data.load_sprites()
    return by_num


def live_num(stage="Rookie"):
    """A real, non-placeholder Digimon num of the given stage, or None if assets
    aren't installed (sprites are gitignored / regenerated by setup_assets.sh)."""
    import tuipet.data.loaders.data as data
    by_num = _by_num()
    return next((n for n, r in by_num.items()
                 if r["stage"] == stage and not data.is_placeholder(n)), None)


@pytest.fixture
def live_pet():
    """A freshly-spawned Rookie from real sprite data (skips if assets missing)."""
    from tuipet.core.pet import Pet
    num = live_num("Rookie")
    if num is None:
        pytest.skip("sprite assets not installed (run tools/setup_assets.sh)")
    p = Pet.from_num(num)
    p.obedience = 500        # out-roll the canon item/food refusal (audit 2026-07)
    return p


# (the futon_item discovery helper left with the staple props:
# strict-DSprite items, 2026-07-17)


@pytest.fixture(autouse=True)
def _sandbox_lobby_feed(tmp_path, monkeypatch):
    """The lobby server module logs public events to FEED_PATH on login/chat/
    disconnect -- any test driving server flows must write a scratch feed, or
    pytest runs append real-looking events to the repo copy (leak found
    2026-07-10: test_bugreport/test_save_integrity grew server/lobby_feed.jsonl
    on every run)."""
    import os as _os
    import sys as _sys
    # import (not just look up) the module: the first test in a session that
    # imports server INSIDE its body used to run before this fixture had
    # anything to patch -- order-dependent sandboxing (test audit 2026-07-13)
    _sys.path.insert(0, _os.path.join(_os.path.dirname(__file__), "..", "server"))
    try:
        import server as srv
    except Exception:
        srv = None
    if srv is not None and hasattr(srv, "FEED_PATH"):
        monkeypatch.setattr(srv, "FEED_PATH", str(tmp_path / "lobby_feed.jsonl"))
    if srv is not None and hasattr(srv, "BUGS_PATH"):
        monkeypatch.setattr(srv, "BUGS_PATH", str(tmp_path / "bugs.jsonl"))
    if srv is not None and hasattr(srv, "LADDER_PATH"):
        monkeypatch.setattr(srv, "LADDER_PATH", str(tmp_path / "ladder.json"))
        monkeypatch.setattr(srv, "LADDER", {"seasons": {}, "claimed": {}})
        srv._ladder_pending.clear()
        srv._ladder_confirm.clear()
        srv._ladder_pair_hour.clear()

@pytest.fixture(autouse=True)
def never_run_pip(monkeypatch):
    """No test may install anything.  The launch auto-updater (2026-07-14) calls
    update.run_upgrade(), and a test that forgot to mock it REALLY RAN pip --
    it upgraded tuipet inside .venv-dev mid-suite.  Same doctrine as
    isolate_save: the suite can never touch the real thing.  A test that wants
    the success path monkeypatches run_upgrade itself; this only stops the real
    one.
    """
    from tuipet.utils import update

    def _refuse(*_a, **_k):
        raise AssertionError(
            "a test tried to shell out to pip -- patch update._RUN "
            "(or mock run_upgrade/upgrade_argv) instead")

    monkeypatch.setattr(update, "_RUN", _refuse)
